group: edge
dist: trusty
language: java
jdk: oraclejdk8
install: true
before_install:
  - sudo apt update
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install docker-compose
  - sudo usermod -aG docker $(whoami)
  # kill pg port 5432
  - true | sudo kill $(sudo lsof -t -i:5432)
script:
  - bash gradlew clean assemble build
  - bash gradlew clean functionalTests
  # manual
  - bash gradlew composeUp
  - bash gradlew loadtestrunner --parallel
  - bash gradlew composeDown
after_script:
  - bash gradlew --stop
cache:
  directories:
    - $HOME/.gradle/
    - .gradle/
