version: "2.1"
services:
  modules-app1:
    #links: ["srv-db:db"]
    #depends_on: [srv-db]
    #environmentonment:
    #  DB_HOST: db
    #command: sh -c "mkdir -f /var/app # not needed with docker-compose"
    extends:
      file: ./compose/docker-compose-base.yml
      service: microservice
    networks: [spring-cloud-turbine]
    ports: ["8001:8001"]
    volumes:
      - "modules-app1-data:/var/app"
      - "./modules/app1/build/libs/app1-0.0.1.jar:/var/app/app.jar:ro"
  infrastructure-hystrix-aggregator:
    extends:
      file: ./compose/docker-compose-base.yml
      service: microservice
    networks: [spring-cloud-turbine]
    ports: ["8002:8002"]
    volumes:
      - "infrastructure-hystrix-aggregator-data:/var/app"
      - "./infrastructure/hystrix-aggregator/build/libs/hystrix-aggregator-0.0.1.jar:/var/app/app.jar:ro"
  infrastructure-hystrix-dashboard:
    extends:
      file: ./compose/docker-compose-base.yml
      service: microservice
    networks: [spring-cloud-turbine]
    ports: ["8003:8003"]
    volumes:
      - "infrastructure-hystrix-dashboard-data:/var/app"
      - "./infrastructure/hystrix-dashboard/build/libs/hystrix-dashboard-0.0.1.jar:/var/app/app.jar:ro"
networks:
  spring-cloud-turbine:
    driver: bridge
volumes:
  infrastructure-hystrix-aggregator-data: {}
  infrastructure-hystrix-dashboard-data: {}
  modules-app1-data: {}
